### ISSUE TITLE
Blib won't delete without speedlimit

### ISSUE THREAD

**Issue by Chiller2019** [zRxnx/zrx_restrictedzone#1]
Hey,

when I create a Zone without speedlimit (Check out off), the Blip won't be deleted. And Its still in the list "to delete zone's"

I got a Error:
![image](https://github.com/zRxnx/zrx_restrictedzone/assets/50303399/6b1b41e4-97d3-4f01-a55c-3b373bd5cd4e)

Kind regards

//BTW ... amazing work!

**Comment by zRxnx** [comment]
Try newest version

**Comment by Chiller2019** [comment]
> Try newest version

Nop, now is the Script destroyed
![image](https://github.com/zRxnx/zrx_restrictedzone/assets/50303399/d6e8d588-3892-4647-88cc-d8488f9eb627)


BTW, what I wanted to mention, if you delete a zone, all zones have the same name, the zone info is also incorrect, there are errors like wrong time ect.

**Comment by zRxnx** [comment]
The new release should finally fix both issues

**Comment by Chiller2019** [comment]
Finally, great work, thx!
